language: go

go:
  - "1.13.x"

addons:
  chrome: stable

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - travis

install:
  - google-chrome 78.0.3904.70
  - chromedriver 78.0.3904.70

script:
  - export WEBDRIVER_PATH=/home/travis/chromedriver
  - export PATH=$PATH:/home/travis/
  - sudo apt-get install -y libgconf-2-4
  - go test

notifications:
  email: false
