language: go

go:
  - "1.13.x"

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - travis

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/
  - export webdriverPath=/home/travis/chromedriver
  - export PATH=$PATH:/home/travis/
  - sudo apt-get install libgconf-2-4
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - go test

notifications:
  email: false