language: go

go:
  - "1.13.x"

addons:
  chrome: stable

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - travis

script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/
  - export WEBDRIVER_PATH=/home/travis/chromedriver
  - export PATH=$PATH:/home/travis/
  - sudo apt-get install -y libgconf-2-4
  - go test

notifications:
  email: false
